# Generated by Django 4.0.4 on 2022-05-08 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Destination Text')),
                ('pos', models.CharField(max_length=255, verbose_name='Pos')),
                ('featured', models.BooleanField(verbose_name='Featured')),
                ('lang', models.CharField(choices=[('BG', 'Bulgarian'), ('CS', 'Czech'), ('DA', 'Danish'), ('DE', 'German'), ('EL', 'Greek'), ('EN-GB', 'British English'), ('EN-US', 'American English'), ('ES', 'Spanish'), ('ET', 'Estonian'), ('FI', 'Finnish'), ('FR', 'French'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('JA', 'Japanese'), ('LT', 'Lithuanian'), ('LV', 'Latvian'), ('NL', 'Dutch'), ('PL', 'Polish'), ('PT-PT', 'Portuguese'), ('PT-BR', 'Brazilian Portuguese'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=8, verbose_name='Destination Language')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_lang', models.CharField(choices=[('BG', 'Bulgarian'), ('CS', 'Czech'), ('DA', 'Danish'), ('DE', 'German'), ('EL', 'Greek'), ('EN-GB', 'British English'), ('EN-US', 'American English'), ('ES', 'Spanish'), ('ET', 'Estonian'), ('FI', 'Finnish'), ('FR', 'French'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('JA', 'Japanese'), ('LT', 'Lithuanian'), ('LV', 'Latvian'), ('NL', 'Dutch'), ('PL', 'Polish'), ('PT-PT', 'Portuguese'), ('PT-BR', 'Brazilian Portuguese'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('SV', 'Swedish'), ('ZH', 'Chinese')], default='DE', max_length=8, verbose_name='Source Language')),
                ('src_text', models.CharField(max_length=500, verbose_name='Source Text')),
                ('tar_text', models.CharField(max_length=500, verbose_name='Target Text')),
                ('tar_lang', models.CharField(choices=[('BG', 'Bulgarian'), ('CS', 'Czech'), ('DA', 'Danish'), ('DE', 'German'), ('EL', 'Greek'), ('EN-GB', 'British English'), ('EN-US', 'American English'), ('ES', 'Spanish'), ('ET', 'Estonian'), ('FI', 'Finnish'), ('FR', 'French'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('JA', 'Japanese'), ('LT', 'Lithuanian'), ('LV', 'Latvian'), ('NL', 'Dutch'), ('PL', 'Polish'), ('PT-PT', 'Portuguese'), ('PT-BR', 'Brazilian Portuguese'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=8, verbose_name='Target Language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'DeTranslation',
                'verbose_name_plural': 'DeTranslations',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Source Text')),
                ('pos', models.CharField(max_length=255, verbose_name='')),
                ('grammar_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Grammar Info')),
                ('featured', models.BooleanField(verbose_name='Featured')),
                ('lang', models.CharField(choices=[('BG', 'Bulgarian'), ('CS', 'Czech'), ('DA', 'Danish'), ('DE', 'German'), ('EL', 'Greek'), ('EN-GB', 'British English'), ('EN-US', 'American English'), ('ES', 'Spanish'), ('ET', 'Estonian'), ('FI', 'Finnish'), ('FR', 'French'), ('HU', 'Hungarian'), ('IT', 'Italian'), ('JA', 'Japanese'), ('LT', 'Lithuanian'), ('LV', 'Latvian'), ('NL', 'Dutch'), ('PL', 'Polish'), ('PT-PT', 'Portuguese'), ('PT-BR', 'Brazilian Portuguese'), ('RO', 'Romanian'), ('RU', 'Russian'), ('SK', 'Slovak'), ('SL', 'Slovenian'), ('SV', 'Swedish'), ('ZH', 'Chinese')], max_length=8, verbose_name='Source Language')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_text', models.CharField(max_length=4096, null=True, verbose_name='Source Example')),
                ('dst_text', models.CharField(max_length=4096, null=True, verbose_name='Destination Example')),
                ('dst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example', to='de_translator.destination', verbose_name='Destination')),
                ('src', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='example', to='de_translator.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
            },
        ),
        migrations.AddField(
            model_name='destination',
            name='src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='de_translator.source', verbose_name='Source'),
        ),
    ]
