# Generated by Django 4.0.4 on 2022-05-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de_translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='featured',
            field=models.BooleanField(blank=True, null=True, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='lang',
            field=models.CharField(choices=[('bg', 'Bulgarian'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ja', 'Japan'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mt', 'Maltese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Solvene'), ('sv', 'Swedish'), ('zh', 'Chinese'), ('de', 'German')], max_length=8, verbose_name='Destination Language'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='pos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pos'),
        ),
        migrations.AlterField(
            model_name='source',
            name='featured',
            field=models.BooleanField(blank=True, null=True, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='source',
            name='lang',
            field=models.CharField(choices=[('bg', 'Bulgarian'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('et', 'Estonian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('it', 'Italian'), ('ja', 'Japan'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mt', 'Maltese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Solvene'), ('sv', 'Swedish'), ('zh', 'Chinese'), ('de', 'German')], default='de', max_length=8, verbose_name='Source Language'),
        ),
        migrations.AlterField(
            model_name='source',
            name='pos',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pos'),
        ),
        migrations.AlterField(
            model_name='source',
            name='text',
            field=models.CharField(help_text='Words you want to translate', max_length=255, verbose_name='Source Text'),
        ),
    ]
